config/routes.rb
Rails.application.routes.draw do
  
  resources :quotations do	
	resources :comments
  end
  
  root 'quotations#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :quotation
  validates :commenter, presence: true,
					length: { minimum: 1 }  
end

app/models/quotation.rb
class Quotation < ApplicationRecord
	has_many :comments
	validates :author, presence: true,
					  length: { minimum: 1 }
	validates :text, presence: true,
					  length: { minimum: 1 }	  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@quotation = Quotation.find(params[:quotation_id])
		@comment = @quotation.comments.create(comment_params)
		redirect_to quotation_path(@quotation)
	
	end
 
	private
		def comment_params
		params.require(:comment).permit(:commenter, :body)
	end
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
	def index
		@quotations = Quotation.all
	end
	
	
	def show
		@quotation = Quotation.find(params[:id])
	end

	
	def new
		@quotation = Quotation.new
	end
	
	
	def create 
		@quotation = Quotation.new(quotation_params)
		
		if @quotation.save

			redirect_to  action: "index"
		else
			render 'new'
		end	
	end
	
	
	private 
		def quotation_params
			params.require(:quotation).permit(:author, :text)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotations and citations</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotations/index.html.erb
<h1>Hello Mr Examinator!</h1>
<%= link_to 'Add a quotation', new_quotation_path %>

<br><br>




<h1>Listing quotations</h1>
 
<table>
  <tr>
    <th>Author</th>
    <th>Citation</th>
    <th></th>
  </tr>
 
  <% @quotations.each do |quotation| %>
    <tr>
      <td><%= quotation.author %></td>
      <td><%= quotation.text %></td>
      <td><%= link_to 'Show', quotation_path(quotation) %></td>
    </tr>
  <% end %>
</table>

app/views/quotations/new.html.erb
<%= form_with scope: :quotation, url:quotations_path, local: true do |form| %>
 
  <% if @quotation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@quotation.errors.count, "mistake") %> my dear, such quotas are no heritage to be worldwided! What's wrong? Look below:
      </h2>
      <ul>
        <% @quotation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


 <p>
    <%= form.label :Author %><br>
    <%= form.text_field :author %>
  </p>
 
  <p>
    <%= form.label :What_did_the_author_say? %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>



<%= link_to 'Return to the list of quotations', quotations_path %>

app/views/quotations/show.html.erb
<p>
  <strong>Author:</strong>
  <%= @quotation.author %>
</p>
 
<p>
  <strong>Said:</strong>
  <%= @quotation.text %>
</p>





<h2>Comments</h2>
<% @quotation.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  ----------
<% end %>






<h2>Add a comment:</h2>
<%= form_with(model: [ @quotation, @quotation.comments.build ], local: true) do |form| %>

  <p>
    <%= form.label :Nickname %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :Comment %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit :Post_your_comment %>
  </p>

  
<% end %>

  
  

<%= link_to 'Return to the list of quotations', quotations_path %>

app/views/welcome/index.html.erb
<h1>Hello world!!!</h1>